const emergencyModel = require("../module/emergencyModule");
const userModel = require("../module/userModule");
const { Resend } = require("resend");

exports.createEmergency = async (req, res) => {
  try {
    const { latitude, longitude, emergencyType } = req.body;

    // Save Emergency
    const emergency = await emergencyModel.create({
      patientId: req.userId,
      latitude,
      longitude,
      emergencyType,
    });

    // Find Logged In User
    const user = await userModel.findById(req.userId);

    if (!user) {
      return res.status(404).json({
        success: false,
        message: "User not found",
      });
    }

    // Emergency Contacts
    const contacts = user.emergencyContacts;
    console.log(contacts);

    if (!contacts || contacts.length === 0) {
      return res.status(400).json({
        success: false,
        message: "No emergency contacts found",
      });
    }

    // Google Maps Link
    const mapLink = `https://www.google.com/maps?q=${latitude},${longitude}`;

    const resend = new Resend("re_4bRR9rwQ_6aomC8wg81cuoNadggRmaSqD");
    // Send Email to Every Emergency Contact
    for (const contact of contacts) {
      if (!contact.email || contact.email.trim() === "") continue;
      try {
        const { data, error } = await resend.emails.send({
          from: "onboarding@resend.dev",
          to: contact.email,
          subject: "🚨 PulseCare Emergency Alert",
          html: `
      <div style="font-family: Arial, sans-serif; max-width:600px; margin:auto; border:1px solid #ddd; border-radius:10px; overflow:hidden;">
        
        <div style="background:#d32f2f; color:white; padding:20px; text-align:center;">
          <h1>🚨 Emergency Alert</h1>
          <p>PulseCare Emergency Notification</p>
        </div>

        <div style="padding:20px;">
          <p>Dear <strong>${contact.name}</strong>,</p>

          <p>
            This is an automated emergency alert from <strong>PulseCare</strong>.
            One of your registered family members has requested immediate assistance.
          </p>

          <table style="width:100%; border-collapse:collapse;">
            <tr>
              <td style="padding:10px; border:1px solid #ddd;"><strong>Patient Name</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">${user.username}</td>
            </tr>

            <tr>
              <td style="padding:10px; border:1px solid #ddd;"><strong>Emergency Type</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">${emergencyType}</td>
            </tr>

            <tr>
              <td style="padding:10px; border:1px solid #ddd;"><strong>Patient Phone</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">${user.phone}</td>
            </tr>

            <tr>
              <td style="padding:10px; border:1px solid #ddd;"><strong>Location</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">
                <a href="${mapLink}" target="_blank">
                  View Live Location
                </a>
              </td>
            </tr>

            <tr>
              <td style="padding:10px; border:1px solid #ddd;"><strong>Date & Time</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">
                ${new Date().toLocaleString()}
              </td>
            </tr>
          </table>

          <p style="margin-top:20px;">
            <strong>Please contact the patient immediately or reach their location as soon as possible.</strong>
          </p>

          <div style="text-align:center; margin:30px 0;">
            <a href="${mapLink}"
               style="background:#d32f2f; color:white; padding:12px 20px; text-decoration:none; border-radius:5px;">
               📍 Open Live Location
            </a>
          </div>
        </div>

        <div style="background:#f5f5f5; padding:15px; text-align:center; font-size:13px; color:#666;">
          This is an automated emergency notification generated by
          <strong>PulseCare Healthcare Platform</strong>.<br>
          Please do not reply to this email.
        </div>

      </div>
    `,
        });
        if (error) {
          console.log("Resend Error:", error);
        } else {
          console.log("Mail Sent:", data);
        }
      } catch (mailError) {
        console.log("Mail Error:", mailError);
      }
    }
    return res.status(201).json({
      success: true,
      message: "Emergency Created Successfully",
      emergency,
    });
  } catch (error) {
    console.log("Emergency Error:", error);
    return res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};
